# path  to sample sheet (CSV format, columns: sample, group, ...)
samples: config/sample_sheet.csv

ref:
  # Define the reference genome to use (must in fasta format, gz compression is not supported). 
  genome: ref/Saccharomyces_cerevisiae.fa
  # Which genome annotation to use.
  annotation: ref/Saccharomyces_cerevisiae.gtf

SRA:
  activate: False
  # If you activate SRA by setting this to `True`, you will have to
  # provide the path of SRA accession files (usually named SRR_Acc_List.txt) 
  # and fulfill the needed information in the sample_sheet.csv file.

  # path to SRA accession list
  acc_list: config/sra.txt
  output_dir: out/SRA/

featureCounts:
  # Define the featureCounts parameters
  attribute_type: gene_id
  feature_type: exon