# path  to sample sheet (CSV format, columns: sample, group, ...)
samples: config/sample_sheet.csv

ref:
  # Define the reference genome to use (must in fasta format, gz compression is not supported). 
  genome: ref/Saccharomyces_cerevisiae.fa
  # Which genome annotation to use.
  annotation: ref/Saccharomyces_cerevisiae.gtf

clean: True
reports: True

# SRA config

SRA:
  activate: false
  # If you run SRA by targeting sra in snakemake, you will have to
  # provide the path of SRA accession files (usually named SRR_Acc_List.txt)
  # and fulfill the needed information in the sample_sheet.csv file.

  # path to SRA accession list
  acc_list: config/sra.txt
  output_dir: SRA/

# RNA-seq upstream config

featureCounts:
  # Define the featureCounts parameters
  attribute_type: gene_id
  feature_type: exon

# Define the newGene parameters
newGene:
  # If you want to activate newGene, set it to True
  activate: True
  # Define the stringtie parameters
  stringtie_params: "-j 1 -c 1 -f 0.01"


# RNA-seq downstream config

PCA:
  activate: False
  # number of dimensions kept in the results (by default 5)
  ncp: 5