name: Sync Github Repos To Gitee

on:
  push:
    branches: 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Sync Github Repos To Gitee  
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/FeelLiao
        dst: gitee/feelliao
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        static_list: "rna-seq-std"
