name: Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches_ignore: []

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Linting
      uses: snakemake/snakemake-github-action@v2.0.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/config/config.yaml --lint"

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Test workflow sra
      uses: snakemake/snakemake-github-action@v2.0.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        stagein: "conda config --set channel_priority flexible"
        args: "sra --configfile .test/config/config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
    - name: Test workflow upstream
      uses: snakemake/snakemake-github-action@v2.0.0
      with:
        directory: .test
        snakefile: workflow/Snakefile
        stagein: "conda config --set channel_priority flexible"
        args: "--configfile .test/config/config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
    # - name: Test workflow report
    #   uses: snakemake/snakemake-github-action@v2.0.0
    #   with:
    #     directory: .test
    #     snakefile: workflow/Snakefile
    #     args: "reports --configfile .test/config/config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"
